version: "3.9"

networks:
  default:
    driver: bridge
  traefik:
    external: true
  docker-socket-proxy:
    internal: true

services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      NETWORKS: 1
    networks:
      - docker-socket-proxy

  traefik:
    image: traefik:v3
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./dynamic_conf.toml:/etc/traefik/dynamic_conf.toml"
      - "./letsencrypt:/letsencrypt"
    depends_on:
      - socket-proxy
    networks:
      - docker-socket-proxy
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      # Traefik complains if no port is set here, this dummy service doesn't exist. See [here](https://github.com/traefik/traefik/issues/5732)
      - "traefik.http.services.justAdummyService.loadbalancer.server.port=1337"
      - "traefik.http.routers.traefik_https.rule=Host(`traefik.${DOMAIN}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik_https.entrypoints=web-secure"
      - "traefik.http.routers.traefik_https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik_https.tls=true"
      - "traefik.http.routers.traefik_https.service=api@internal"
      - "traefik.http.routers.traefik_https.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH_USER}:${BASIC_AUTH_PASSWORD_HASH}"
      - "traefik.http.routers.http_traefik.rule=Host(`traefik.${DOMAIN}`) &&(PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.http_traefik.entrypoints=web"
      - "traefik.http.routers.http_traefik.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"

      - "traefik.http.routers.https-redirect.entrypoints=web"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.https-redirect.tls.options=default"
      - "traefik.http.routers.https-redirect.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
