[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[api]
  insecure = false
  dashboard = true

[providers.docker]
  endpoint = "tcp://socket-proxy:2375"
  exposedByDefault = false

[providers.file]
  filename = "/etc/traefik/dynamic_conf.toml"

[entryPoints]
  [entryPoints.web]
    address = ":80"
    http.redirections.entryPoint.to = "web-secure"
    http.redirections.entryPoint.scheme = "https"

  [entryPoints.web-secure]
    address = ":443"